spring:
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:instagram}  # Railway? ???? DATABASE_URL ??
    username: ${PGUSER:sa}
    password: ${PGPASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  jpa:
    hibernate:
      ddl-auto: update  # create ?? update (??? ??)
    show-sql: false
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}

  h2:
    console:
      enabled: false  # ??????? ????

server:
  port: ${PORT:8080}